/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pi' at '3/6/15 5:19 PM' with Gradle 2.3
 *
 * @author pi, @date 3/6/15 5:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
